### PR TITLE
Adjust DI usage to workaround Host v4 bug

### LINKED ISSUE #359: Functions Host v4 is not supported
We require the root `IServiceProvider` to be available when initializing the endpoint. This is done on the first request but Host v4 now executes functions with a scoped provider. This means that we will get access to a IServiceProvider that will be disposed of after the first call resulting in 
 
```
[2021-11-18T14:58:45.221Z] Executed 'NServiceBusFunctionEndpointTrigger-InProcess-HostV4' (Failed, Id=acd86500-4424-4506-90ea-b5aa23cf94c8, Duration=56ms)
[2021-11-18T14:58:45.223Z] System.Private.CoreLib: Exception while executing function: NServiceBusFunctionEndpointTrigger-InProcess-HostV4. Microsoft.Azure.WebJobs.Script.WebHost: Container is disposed and should not be used: Container is disposed.
```

### PR DESCRIPTION
**Pull request by andreasohlund**
This PR avoid the use of `AddSingleton<T>(Func<ISerrviceProvider,T> f)` that causes the functions runtime v4 to pass a scoped IServiceProvider to singletons rather than the expected root singleton.

This PR also:

- Adds some more assembly excludes that seems to be needed for host v4
- Adds a test project to test host v3 and v4 manually

Fixes #359

### CODE REVIEW

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs [hunk 1]
```diff
@@ -81,25 +81,23 @@ public static partial class FunctionsHostBuilderExtensions
...
+                serviceBusTriggeredEndpointConfiguration.AdvancedConfiguration,
                 functionsHostBuilder.Services,
                 Path.Combine(functionsHostBuilder.GetContext().ApplicationRootPath, "bin"));
 
-            // for backward compatibility
-            functionsHostBuilder.Services.AddSingleton(endpointFactory);
+            functionsHostBuilder.Services.AddSingleton(serviceBusTriggeredEndpointConfiguration);
+            functionsHostBuilder.Services.AddSingleton(startableEndpoint);
+            functionsHostBuilder.Services.AddSingleton<FunctionEndpoint>();
             functionsHostBuilder.Services.AddSingleton<IFunctionEndpoint>(sp => sp.GetRequiredService<FunctionEndpoint>());
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: Why not kill this one once and for all and make the FunctionEndpoint internal? We added this once for backward compatibility but if we change the generator to use the interface too, there is little reason to ever use the class directly

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs [hunk 2]
```diff
@@ -81,25 +81,23 @@ public static partial class FunctionsHostBuilderExtensions
         static void RegisterEndpointFactory(IFunctionsHostBuilder functionsHostBuilder,
             ServiceBusTriggeredEndpointConfiguration serviceBusTriggeredEndpointConfiguration)
         {
-            // Provides a function to locate the file system directory containing the binaries to be loaded and scanned.
             // When using functions, assemblies are moved to a 'bin' folder within FunctionsHostBuilderContext.ApplicationRootPath.
-            var endpointFactory = Configure(
-                serviceBusTriggeredEndpointConfiguration,
+            var startableEndpoint = Configure(
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:85]: With this change, is there a risk that we do things too early? I guess not really since the `IStartableEndpointWithExternallyManagedContainer` only registers stuff and never resolves, right?

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: Not sure, eg for the worker it was help full to be able to have customers workaround the binding issues by skipping our generator and manually add the hook? (no strong opinion tho)

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 2 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:85]: As far as I can tell the old code also created the startable endpoint at the same point in time

https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/361/files/a659ab987504e40a052ff1246ac1f7addac1f6c1#diff-306b3814fac030a6fce663f65dbfe10a2ee012bc6c23a9a36741e7116f4eca4bL111

can you confirm?

Comment (danielmarbach) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:85]: No it was lazy executed on first resolve which means later in the runtime

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (danielmarbach) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: When we introduced the workaround we said customers should be using the interface only actually

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 2 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:85]: Ah, good catch. All tests work fine and manual tests on v3 + v4 host as well so I think we're good.

That said, since its not needing the builder we can delay it I guess?

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs [hunk 3]
```diff
@@ -73,7 +78,13 @@ await Process(message, NoTransactionStrategy.Instance, pipeline, cancellationTok
                 .ConfigureAwait(false);
         }
 
-        internal static readonly string[] AssembliesToExcludeFromScanning = { "NCrontab.Signed.dll" };
+        internal static readonly string[] AssembliesToExcludeFromScanning = {
+            "NCrontab.Signed.dll",
```
Comment (SeanFeldman) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:82]: Is there a related issue to move this list into Core?

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (SeanFeldman) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: >Not sure, eg for the worker it was help full to be able to have customers workaround the binding issues by skipping our generator and manually add the hook? (no strong opinion tho)

When that happens, they'd be still invoking `IFunctionEndpoint` injected into the their custom trigger function, no? And if so, `FunctionEndpoint` would not be necessary.

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs (hunk 3 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:82]: I'll raise one once this is merged

**Comment by andreasohlund** [comment]
>When that happens, they'd be still invoking IFunctionEndpoint injected into the their custom trigger function, no? And if so, FunctionEndpoint would not be necessary.

Makes sense (cc @danielmarbach ), I'll do that as a separate PR since its not strictly related and will make backporting of this change easier

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: Could make it work and after talking to @danielmarbach we think the current approach is better since that would surface configuration issues immediately rather than on the first invocation

**Comment by andreasohlund** [comment]
MS issue raised https://github.com/Azure/azure-functions-host/issues/7874

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs (hunk 3 above)
Comment (timbussmann) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:82]: not sure why this should be added to core. This is only an issue due to the in-process hosting model that uses NCrontab in the inprocess executable folders while some triggers might also bring it in. Core has 0 problems loading this, this is only limited to the inprocess hosting model.

Comment (SeanFeldman) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:82]: The comment was for the whole list, not a specific assembly that happened to be on the top of the list.

Comment (timbussmann) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:82]: but doesn't the same reason apply to all the other assemblies in that list too?

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 2 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:85]: Decided to go with the current solution to make sure to surface config issues earlier

**Comment by andreasohlund** [comment]
@danielmarbach making `FunctionEndpoint` internal results in 

```
DryIoc.ContainerException
  HResult=0x80131509
  Message=Unable to get constructor of NServiceBus.FunctionEndpoint using provided constructor selector when resolving singleton NServiceBus.FunctionEndpoint {ReturnDefault} #158
  from scoped container with {no name}.
  Source=Microsoft.Azure.WebJobs.Script.WebHost
  StackTrace:
   at DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7070
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6547
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6627
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at NServiceBus.FunctionsHostBuilderExtensions.<>c.<RegisterEndpointFactory>b__4_0(IServiceProvider sp) in C:\dev\NServiceBus.AzureFunctions.InProcess.ServiceBus\src\NServiceBus.AzureFunctions.InProcess.ServiceBus\FunctionsHostBuilderExtensions.cs:line 93
   at DryIoc.Microsoft.DependencyInjection.DryIocAdapter.<>c__DisplayClass3_0.<RegisterDescriptor>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\DryIocAdapter.cs:line 156
   at DryIoc.Registrator.<>c__DisplayClass27_0.<RegisterDelegate>b__0(IResolverContext r) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 4543
   at DryIoc.Factory.<>c__DisplayClass26_0.<ApplyReuse>b__2() in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6598
   at DryIoc.Scope.TryGetOrAdd(ImMap`1 items, Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7842
   at DryIoc.Scope.GetOrAdd(Int32 id, CreateScopedValue createValue, Int32 disposalOrder) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7827
   at DryIoc.Factory.ApplyReuse(Expression serviceExpr, Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6597
   at DryIoc.Factory.GetExpressionOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6557
   at DryIoc.Factory.GetDelegateOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 6627
   at DryIoc.DelegateFactory.GetDelegateOrDefault(Request request) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 7739
   at DryIoc.Container.ResolveAndCacheDefaultFactoryDelegate(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 210
   at DryIoc.Container.DryIoc.IResolver.Resolve(Type serviceType, IfUnresolved ifUnresolved) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\DryIoc\Container.cs:line 195
   at Microsoft.Azure.WebJobs.Script.WebHost.DependencyInjection.ScopedServiceProvider.GetService(Type serviceType) in D:\a\1\s\src\WebJobs.Script.WebHost\DependencyInjection\ScopedServiceProvider.cs:line 25
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IServiceProvider serviceProvider) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 37
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultJobActivator.CreateInstance[T](IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DefaultJobActivator.cs:line 32
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.<>c__DisplayClass1_1.<.ctor>b__0(IFunctionInstanceEx i) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 20
   at Microsoft.Azure.WebJobs.Host.Executors.ActivatorInstanceFactory`1.Create(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ActivatorInstanceFactory.cs:line 26
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionInvoker`2.CreateInstance(IFunctionInstanceEx functionInstance) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionInvoker.cs:line 44
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.Initialize() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 776
   at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.<TryExecuteAsync>d__16.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 102

```

so lets deal with that separately.

This should be good for final review now

**Comment by danielmarbach** [comment]
@andreasohlund I think the generator doesn't use the interface. That's why you get that exception

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]: The comment `// for backward compatibility` was meant to be for the lambda singleton registration. Given the danger of lambda registrations, why don't we remove it entirely and bite the bullet with the breaking change by also making `FunctionEndpoint` internal and changing the registration to

`functionsHostBuilder.Services.AddSingleton<IFunctionEndpoint, FunctionEndpoint>();`

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs [hunk 4]
```diff
@@ -18,8 +18,13 @@
...
     {
-        // This ctor is used for the FunctionsHostBuilder scenario where the endpoint is created already during configuration time using the function host's container.
-        internal FunctionEndpoint(IStartableEndpointWithExternallyManagedContainer externallyManagedContainerEndpoint, ServiceBusTriggeredEndpointConfiguration configuration, IServiceProvider serviceProvider)
+        /// <summary>
+        /// Creates the function endpoint.
+        /// </summary>
+        /// <param name="externallyManagedContainerEndpoint">The startable endpoint.</param>
+        /// <param name="configuration">Configuration to use.</param>
+        /// <param name="serviceProvider">The service provider managed by the functions host.</param>
+        public FunctionEndpoint(IStartableEndpointWithExternallyManagedContainer externallyManagedContainerEndpoint, ServiceBusTriggeredEndpointConfiguration configuration, IServiceProvider serviceProvider)
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:27]: Could this be made internal again?

File: src/ManualTests.HostV3/Startup.cs [hunk 5]
```diff
@@ -0,0 +1,13 @@
+using Microsoft.Azure.Functions.Extensions.DependencyInjection;
+using NServiceBus;
+
+[assembly: FunctionsStartup(typeof(Startup))]
+[assembly: NServiceBusTriggerFunction("InProcess-HostV3")]
+
+public class Startup : FunctionsStartup
```
Comment (danielmarbach) [inline src/ManualTests.HostV3/Startup.cs:7]: Is there a good way to kill this manuel test project and reproduce the bug with an automated test?

**Comment by YodasMyDad** [comment]
Just wondering when this will be merged? It's completely blocking me from using Azure Functions at the moment.

**Comment by andreasohlund** [comment]
We're going to make this a priority so stay tuned

**Comment by andreasohlund** [comment]
@danielmarbach made the changes we talked about

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs [hunk 6]
```diff
@@ -81,38 +81,34 @@ public static partial class FunctionsHostBuilderExtensions
...
                 functionsHostBuilder.Services,
                 Path.Combine(functionsHostBuilder.GetContext().ApplicationRootPath, "bin"));
 
-            // for backward compatibility
-            functionsHostBuilder.Services.AddSingleton(endpointFactory);
-            functionsHostBuilder.Services.AddSingleton<IFunctionEndpoint>(sp => sp.GetRequiredService<FunctionEndpoint>());
+            functionsHostBuilder.Services.AddSingleton(serviceBusTriggeredEndpointConfiguration);
+            functionsHostBuilder.Services.AddSingleton(startableEndpoint);
+            functionsHostBuilder.Services.AddSingleton<InProcessFunctionEndpoint>();
+            functionsHostBuilder.Services.AddSingleton<IFunctionEndpoint>(sp => sp.GetRequiredService<InProcessFunctionEndpoint>());
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs:93]:
```suggestion
            functionsHostBuilder.Services.AddSingleton<IFunctionEndpoint, InProcessFunctionEndpoint>();
```

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/IFunctionEndpoint.cs [hunk 7]
```diff
@@ -13,12 +13,12 @@
...
     /// messages explicitly passed to it by the caller.
     /// </summary>
-    public partial interface IFunctionEndpoint
+    public interface IFunctionEndpoint
     {
         /// <summary>
         /// Processes a message received from an AzureServiceBus trigger using the NServiceBus message pipeline. This method will lookup the <see cref="ServiceBusTriggerAttribute.AutoComplete"/> setting to determine whether to use transactional or non-transactional processing.
         /// </summary>
-        Task Process(Message message, ExecutionContext executionContext, IMessageReceiver messageReceiver, ILogger functionsLogger = null, CancellationToken cancellationToken = default);
+        Task Process(Message message, ExecutionContext executionContext, IMessageReceiver messageReceiver, ILogger functionsLogger, bool enableCrossEntityTransactions, CancellationToken cancellationToken = default);
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/IFunctionEndpoint.cs:21]: Is functions logger now mandatory? Why? Could both functions logger and the flag be non-mandatory?

File: src/ServiceBus.AcceptanceTests/FunctionEndpointComponent.cs [hunk 8]
```diff
@@ -123,7 +122,7 @@ public override Task Stop()
             readonly ScenarioContext scenarioContext;
             readonly Type functionComponentType;
             IList<object> messages;
-            FunctionEndpoint endpoint;
+            InProcessFunctionEndpoint endpoint;
```
Comment (danielmarbach) [inline src/ServiceBus.AcceptanceTests/FunctionEndpointComponent.cs:125]: Maybe use the interface here too?

File: src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs [hunk 9]
```diff
@@ -35,17 +34,17 @@ public async Task Should_load_handlers_from_assembly_when_using_FunctionsHostBui
...
                 Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ExternalHandlers"));
 
             var serviceProvider = serviceCollection.BuildServiceProvider();
-            var endpoint = endpointFactory(serviceProvider);
+            var endpoint = new InProcessFunctionEndpoint(startableEndpoint, configuration, serviceProvider);
 
 
             // we need to process an actual message to have the endpoint being created
-            await endpoint.ProcessNonTransactional(GenerateMessage(), new ExecutionContext(), null, default, default);
+            await endpoint.ProcessNonTransactional(GenerateMessage(), new ExecutionContext(), default, default);
```
Comment (danielmarbach) [inline src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs:47]: Why not go over the interface method here? Do we have InternalsVisibleTo?

File: src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator.cs [hunk 10]
```diff
@@ -8,14 +8,14 @@
     [Generator]
     public class TriggerFunctionGenerator : ISourceGenerator
     {
-        internal static readonly DiagnosticDescriptor InvalidEndpointNameError = new DiagnosticDescriptor(id: "NSBFUNC001",
+        internal static readonly DiagnosticDescriptor InvalidEndpointNameError = new DiagnosticDescriptor(id: "NSBFUNC003",
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator.cs:11]: For my understanding, why did we have to move the diagnostic ID?

File: src/ServiceBus.Tests/ReflectionHelperTests.cs [hunk 11]
```diff
@@ -1,148 +0,0 @@
-﻿namespace ServiceBus.Tests
-{
-    using System;
-    using Microsoft.Azure.ServiceBus;
-    using Microsoft.Azure.WebJobs;
-    using NServiceBus.AzureFunctions.InProcess.ServiceBus;
-    using NUnit.Framework;
-
-    [TestFixture]
-    public class ReflectionHelperTests
```
Comment (danielmarbach) [inline src/ServiceBus.Tests/ReflectionHelperTests.cs:10]: By removing the reflection helper would we break a scenario when people did use the function endpoint directly and not the generated approach?

File: src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator2.cs [hunk 12]
```diff
@@ -1,145 +0,0 @@
-﻿namespace NServiceBus.AzureFunctions.SourceGenerator
-{
-    using System.Text;
-    using Microsoft.CodeAnalysis;
-    using Microsoft.CodeAnalysis.CSharp.Syntax;
-    using Microsoft.CodeAnalysis.Text;
-
-    [Generator]
-    public class TriggerFunctionGenerator2 : ISourceGenerator
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator2.cs:9]: Why did we have two generators? And why is it possible now to remove them?

File: src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator.cs (hunk 10 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.SourceGenerator/TriggerFunctionGenerator.cs:11]: Good point, we had 2 since we at one point in time had 2 generators. Will  make it `NSBFUNC001` since we only have one now

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs (hunk 1 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionsHostBuilderExtensions.cs]: Removed

File: src/ServiceBus.Tests/ReflectionHelperTests.cs (hunk 11 above)
Comment (andreasohlund) [reply src/ServiceBus.Tests/ReflectionHelperTests.cs:10]: Since the user would create the function binding explicitly they would already know the value of "AutoComplete" so no need for us to provide a reflection helper to get at it

**Comment by andreasohlund** [comment]
@danielmarbach made the changes we talked about. Removing the internals visible seems quite tricky so I'll do that in a separate PR since its not strictly related to this

File: src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs (hunk 9 above)
Comment (danielmarbach) [reply src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs:47]: Here we could still call the public API

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs [hunk 13]
```diff
@@ -58,11 +54,11 @@ await Process(message, new MessageReceiverTransactionStrategy(message, messageRe
             }
         }
 
-        /// <summary>
-        /// Processes a message received from an AzureServiceBus trigger using the NServiceBus message pipeline.
-        /// </summary>
-        public async Task ProcessNonTransactional(Message message, ExecutionContext executionContext,
-            IMessageReceiver messageReceiver, ILogger functionsLogger = null, CancellationToken cancellationToken = default)
+        public async Task ProcessNonTransactional(
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs:57]: Could we already make these private?

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs [hunk 14]
```diff
@@ -6,37 +6,33 @@
...
+            CancellationToken cancellationToken) =>
+            enableCrossEntityTransactions
+                ? ProcessTransactional(message, executionContext, messageReceiver, functionsLogger, cancellationToken)
+                : ProcessNonTransactional(message, executionContext, functionsLogger, cancellationToken);
 
-        /// <summary>
-        /// Processes a message received from an AzureServiceBus trigger using the NServiceBus message pipeline. All messages are committed transactionally with the successful processing of the incoming message.
-        /// <remarks>Requires <see cref="ServiceBusTriggerAttribute.AutoComplete"/> to be set to false!</remarks>
-        /// </summary>
         public async Task ProcessTransactional(Message message, ExecutionContext executionContext,
```
Comment (danielmarbach) [inline src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs:36]: Could we already make these private?

**Review by danielmarbach — APPROVED** [review]

File: src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs (hunk 9 above)
Comment (andreasohlund) [reply src/ServiceBus.Tests/When_shipping_handlers_in_dedicated_assembly.cs]: Fixed

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs (hunk 13 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs]: yes, done

File: src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs (hunk 14 above)
Comment (andreasohlund) [reply src/NServiceBus.AzureFunctions.InProcess.ServiceBus/InProcessFunctionEndpoint.cs]: yes, done
